### ISSUE TITLE
transaction error ,  signature is not valid for Curve: ECDSA_secp256k1

### ISSUE THREAD

**Issue by TracyH1988** [the-nft-company/flow-jvm-sdk#11]
### Problem

if the pub key Curve is ECDSA_secp256k1, if there is one signature,it will be failed

ERROR MESSAGE:

FlowTransactionResult(status=SEALED, statusCode=1, errorMessage=[Error Code: 1006] invalid proposal key: public key 3 on account xxxxxxxxx does not have a valid signature: [Error Code: 1009] invalid envelope key: public key 3 on account xxxxxxxxxxxx does not have a valid signature: signature is not valid, events=[])

Because the flow-jvm-sdk can not support it by default, only support ECDSA_P256

### Steps to Reproduce 
env :  mainnet
1. ensure one pub key Curve is ECDSA_secp256k1
2. sign it by private key  and SHA3_256
3. error happened ....

  
### Context

newer in flow,  interest in it,  hope guys can fix it, or did I miss something?

**Comment by briandilley** [comment]
Can you please submit a pull request with a unit test exhibiting this behavior?
